### ISSUE TITLE
Can this tool extract graphics from new champion sc files?

### ISSUE THREAD

**Issue by hiendo3d** [baraklevy20/Supercell-Extractor#6]
<img width="830" alt="fixed" src="https://user-images.githubusercontent.com/99595169/161249137-d1fb3561-c961-4f7f-b930-363412ec1916.png">
I'm following the tutorial but can't decode dl.sc or any .sc files.
Can you fix this issue?
https://drive.google.com/file/d/1AwgUax0446zJS8luCL3DeyXSJApDe5mt/view?usp=sharing

**Comment by baraklevy20** [comment]
@hiendo3d Hi, what game is it from, and what version?

**Comment by hiendo3d** [comment]
it's from newest Clash Royale update

**Comment by baraklevy20** [comment]
On Android or iOS?

**Comment by hiendo3d** [comment]
Thank you. I try the compress files, It's working
